env: standard
service: storefront
runtime: nodejs10
instance_class: F1

automatic_scaling:
  max_instances: 1

handlers:
- url: /.*
  script: auto
  secure: always
  redirect_http_response_code: 301

env_variables:
  BACKEND_URL: https://chetabahana.appspot.com/id/
